# Basic
title: 棕熊的肚皮
subtitle: 海纳百川，有容乃大
welcome_message: Welcome TarlorChun's world
description: SLAM　小白
creator: <a href="#">@TailorChun</a>

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: Blog列表
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'https://github.com/zhousunchun/zhousunchun.github.io'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

categeries:
    - {title: SLAM, description: SLAM学习, url: '/category/slam/index.html'}
    - {title: C++, description: C++学习, url: '/category/c++/index.html'}
    - {title: Practice, description: 代码实践, url: '/category/practice/index.html'}
    - {title: Talk, description: 技术杂谈, url: '/category/talk/index.html'}
    - {title: Tools, description: 实用工具介绍, url: '/category/tools/index.html'}
    #- {title: network, description: 网络协议, url: '/category/network/index.html'}
# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment 这是disqus的评论系统
comment:
    disqus: abbott-king
    # duoshuo:

# Social

social:
#    weibo: abbottking
    github: zhousunchun
#    twitter: mrjinyb
#    gplus: 109069755103858985204
    mail: zhousunchun@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host

leancloud:
  enable: true
  app_id: dywMPzRcBYesEIViNkYb2rV6-gzGzoHsz
  app_key: p28m9n8mbjADPCgiuLekxmIe

#leancloud:
#  enable: true
#  app_id: n9H2t3VFwwMPqC0rSYfvlJuu-gzGzoHsz
#  app_key: DkeWUHsd9YIYIsnKRg6vw1Lk
